version: '3'

networks:
  laravel:

services:
  php:
    container_name: php_container
    image: php:7.4-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - laravel

    
    nginx:
      container_name: nginx_container
      image: nginx:alpine
      ports:
        - "8080:80"
      volumes: 
        - ./src:/code
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - laravel